### ISSUE TITLE
Can't run Example app

### ISSUE THREAD

**Issue by z3ro-cool** [AshKyd/ui95#1]
Hi @AshKyd, 

First of all, this project is really incredible, I've been looking for something like this for months, and I'm still amazed by everything you achieved here!

However, I've been trying to run the example app, and despite following all steps, it keeps showing just a blue/green screen. It appears something is missing or maybe a broken code somewhere. 

I was hoping you could help with this, maybe I'm doing something wrong or searching at the wrong places.

Thanks!

**Comment by AshKyd** [comment]
I tried this out, and it looks like the Webamp component was breaking the build. The example app started working when I removed it 👍 

This is just a hobby project, so if it's still not working for you after that I don't think I can help you. But let me know how you do
