### ISSUE TITLE
Example App - Build Error Unterminated regular expression (3977:83)

### ISSUE THREAD

**Issue by Aiyush-G** [AshKyd/ui95#2]
Hi, 

Can I start by saying how amazing this project is! I am kinda a noob at coding so I think I have gone wrong somewhere here but I get a "Unterminated regular expression (3977:83)" build error.

Steps to reproduce:

```
cd "ui95-master"
npm install
npm run watch-example
```

But then I get the error:

🚨 Build Error

```
/Users/name/Documents/folder/folder/folder/ui95-master/node_modules/webamp/built/webamp.bundle.js:3977:83: Unterminated regular expression (3977:83)

  3975 | 	if (sourceMap) {
  3976 | 		// http://stackoverflow.com/a/26603875
> 3977 | 		css += "\n + btoa(unescape(encodeURIComponent(JSON.stringify(sourceMap)))) + " */";
       | 		                                                                                ^
  3978 | 	}
  3979 | 
  3980 | 	var blob = new Blob([css], { type: "text/css" });
```

Do you know what is causing this?

Thanks

**Comment by AshKyd** [comment]
This was something hinky in Webamp. I ended up removing itfrom the repo because I was seeing similar issues and wasn't using it anyway.
